// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: channels.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, created_at, updated_at, channel, channelid, region, prio, oshi, gen, tags, company)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, created_at, updated_at, channel, channelid, region, prio, oshi, gen, tags, company
`

type CreateChannelParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	Channel   string
	Channelid string
	Region    string
	Prio      sql.NullBool
	Oshi      sql.NullBool
	Gen       sql.NullInt32
	Tags      sql.NullString
	Company   sql.NullString
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Channel,
		arg.Channelid,
		arg.Region,
		arg.Prio,
		arg.Oshi,
		arg.Gen,
		arg.Tags,
		arg.Company,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Channel,
		&i.Channelid,
		&i.Region,
		&i.Prio,
		&i.Oshi,
		&i.Gen,
		&i.Tags,
		&i.Company,
	)
	return i, err
}

const getChannel = `-- name: GetChannel :one
SELECT id, created_at, updated_at, channel, channelid, region, prio, oshi, gen, tags, company FROM channels
WHERE channelid = $1
`

func (q *Queries) GetChannel(ctx context.Context, channelid string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, channelid)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Channel,
		&i.Channelid,
		&i.Region,
		&i.Prio,
		&i.Oshi,
		&i.Gen,
		&i.Tags,
		&i.Company,
	)
	return i, err
}

const getChannelIDs = `-- name: GetChannelIDs :many
SELECT channelid FROM channels
`

func (q *Queries) GetChannelIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getChannelIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var channelid string
		if err := rows.Scan(&channelid); err != nil {
			return nil, err
		}
		items = append(items, channelid)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
