// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Channel struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Channel   string
	Channelid string
	Region    string
	Prio      sql.NullBool
	Oshi      sql.NullBool
	Gen       sql.NullInt32
	Tags      sql.NullString
	Company   sql.NullString
}
