// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: playlists.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (id, created_at, updated_at, channelID, playlistID)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, channelid, playlistid
`

type CreatePlaylistParams struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	Channelid  string
	Playlistid string
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, createPlaylist,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Channelid,
		arg.Playlistid,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Channelid,
		&i.Playlistid,
	)
	return i, err
}
